### ISSUE TITLE
[17:05:01] [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\entity\object\PrimedTNT::getName()" (EXCEPTION) in "plugins/BountyPE/src/Infernus101/Main" at line 123

### ISSUE THREAD

**Issue by SuperAdam47** [Zedstar16/BountyPE#3]
error[17:05:01] [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\entity\object\PrimedTNT::getName()" (EXCEPTION) in "plugins/BountyPE/src/Infernus101/Main" at line 123

**Comment by SuperAdam47** [comment]
@Zedstar16

**Comment by Zedstar16** [comment]
Solved
